//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezerwacjeClient.UsersServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/RezerwacjeService")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/RezerwacjeService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersServiceReference.IUsersService")]
    public interface IUsersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/FindAll", ReplyAction="http://tempuri.org/IUsersService/FindAllResponse")]
        RezerwacjeClient.UsersServiceReference.Users[] FindAll(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/FindAll", ReplyAction="http://tempuri.org/IUsersService/FindAllResponse")]
        System.Threading.Tasks.Task<RezerwacjeClient.UsersServiceReference.Users[]> FindAllAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/FindByLogin", ReplyAction="http://tempuri.org/IUsersService/FindByLoginResponse")]
        RezerwacjeClient.UsersServiceReference.Users FindByLogin(string sessionId, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/FindByLogin", ReplyAction="http://tempuri.org/IUsersService/FindByLoginResponse")]
        System.Threading.Tasks.Task<RezerwacjeClient.UsersServiceReference.Users> FindByLoginAsync(string sessionId, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/isAdmin", ReplyAction="http://tempuri.org/IUsersService/isAdminResponse")]
        bool isAdmin(string sessionID, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/isAdmin", ReplyAction="http://tempuri.org/IUsersService/isAdminResponse")]
        System.Threading.Tasks.Task<bool> isAdminAsync(string sessionID, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IUsersService/GetDataUsingDataContractResponse")]
        RezerwacjeClient.UsersServiceReference.CompositeType GetDataUsingDataContract(RezerwacjeClient.UsersServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IUsersService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<RezerwacjeClient.UsersServiceReference.CompositeType> GetDataUsingDataContractAsync(RezerwacjeClient.UsersServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersServiceChannel : RezerwacjeClient.UsersServiceReference.IUsersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceClient : System.ServiceModel.ClientBase<RezerwacjeClient.UsersServiceReference.IUsersService>, RezerwacjeClient.UsersServiceReference.IUsersService {
        
        public UsersServiceClient() {
        }
        
        public UsersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RezerwacjeClient.UsersServiceReference.Users[] FindAll(string sessionId) {
            return base.Channel.FindAll(sessionId);
        }
        
        public System.Threading.Tasks.Task<RezerwacjeClient.UsersServiceReference.Users[]> FindAllAsync(string sessionId) {
            return base.Channel.FindAllAsync(sessionId);
        }
        
        public RezerwacjeClient.UsersServiceReference.Users FindByLogin(string sessionId, string login) {
            return base.Channel.FindByLogin(sessionId, login);
        }
        
        public System.Threading.Tasks.Task<RezerwacjeClient.UsersServiceReference.Users> FindByLoginAsync(string sessionId, string login) {
            return base.Channel.FindByLoginAsync(sessionId, login);
        }
        
        public bool isAdmin(string sessionID, string login) {
            return base.Channel.isAdmin(sessionID, login);
        }
        
        public System.Threading.Tasks.Task<bool> isAdminAsync(string sessionID, string login) {
            return base.Channel.isAdminAsync(sessionID, login);
        }
        
        public RezerwacjeClient.UsersServiceReference.CompositeType GetDataUsingDataContract(RezerwacjeClient.UsersServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<RezerwacjeClient.UsersServiceReference.CompositeType> GetDataUsingDataContractAsync(RezerwacjeClient.UsersServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
